### ISSUE TITLE
Feature request: Drought indices

### ISSUE THREAD

**Issue by khider** [Ouranosinc/xclim#973] opened 2022-01-08 00:02 UTC
It would also be convenient to add some drought indices. This package is useful: https://climate-indices.readthedocs.io/en/latest/

The code can be called outside the command line and be made to work with `apply_ufunc` as in: https://github.com/mintproject/droughtIndices/blob/d1149ba63f275b5a4531fbd6a6cadefaef90ecc2/WM_climate_indices.py#L369

**Comment by tlogan2000** [comment] 2022-01-10 13:15
Hello @khider. Thanks for your interest. We are actually hoping to have an intern look at incorporating these exact indices this summer.

**Comment by huard** [comment] 2022-01-10 18:30
Duplicate of #131.

**Closed by huard** 2022-01-10 18:30 UTC
